#Server
server:
  port: 8081

#DataBase
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  flyway:
    url: ${POSTGRES_DB_URL}
    locations: classpath:db/migration
    user: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    validate-migration-naming: true

#JWT tokens
jwt:
  password:
    encoder:
      secret: ${ENCODER_SECRET}
      iteration: ${ENCODER_ITERATION}
      keylength: ${ENCODER_KEY_LENGTH}
  secret:
    access: ${ENCODER_SECRET_ACCESS}
    refresh: ${ENCODER_SECRET_REFRESH}
    expiration_access_token: ${EXPIRATION_ACCESS_TOKEN}
    expiration_refresh_token: ${EXPIRATION_REFRESH_TOKEN}
    issuer: ${ISSUER}
    key: ${SECRET}

#OpenApi
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
